### PR TITLE
Display Italic fonts (Windows)

### PR DESCRIPTION
**Pull request by jdrouhard**
This implements feature request #198.

Escape code for turning italics on is `^[[3m`, off is `^[[23m`. I added support for setting an `ITALIC` attribute when the correct escape codes are processed. When the attribute is set, attempt to use the italic version of the configured font. If the italic font is a different size than the normal font, discard it (as we do with bold or underline fonts) and use normal font instead.

The use of the italic font is only enabled by a new configuration setting which defaults to on.

### CODE REVIEW

**Comment by johnmiked15** [comment]
Any chance of this getting merged in soon?

**Comment by Congee** [comment]
Anything blocking this PR?

**Comment by szepeviktor** [comment]
@FauxFaux Please merge this one.

**Comment by johnmiked15** [comment]
@FauxFaux  How goes development of PuTTYTray? Any more updates on what I need to do to get this merged in?

**Pull request closed without merging**
